# Não use a estratégia Recreate - aqui apenas um exemplo do que não fazer
# Lembre-se que por padrão a estratégia adotada é RollingUpdate

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx
  selector:
    matchLabels:
      type: frontend
  strategy:
    type: Recreate
  replicas: 6
